name: Build and Release Jars

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Build and collect jars
        run: ./gradlew chiseledBuildAndCollect

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.$GH_TOKEN }}

      - name: Upload JAR assets
        run: |
          for jar in build/chiseled-jars/*.jar; do
            curl -s -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/java-archive" \
              --data-binary "@$jar" \
              "${{ steps.create_release.outputs.upload_url }}?name=$(basename "$jar")"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.$GH_TOKEN }}
